### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by pnrobinson**

### CODE REVIEW

**Comment by pnrobinson** [comment]
@ielis please take a look at validate.rst

**Comment by hrshdhgd** [comment]
@pnrobinson , I have added a new page for [examples](http://phenopackets.org/phenopacket-tools/examples.html). It is very basic as of now and doesn't include `cohorts` since there are no YAML files generated under that directory.

@ielis , for now I have implemented a simple find jar in `phenopacket-tools-cli/target/` directory and it seems to work fine. We can always think of better ways to do this if need be.

**Comment by pnrobinson** [comment]
@hrshdhgd not sure how to test this without actually merging. Should we go ahead and then make any additional changes later on?

**Comment by hrshdhgd** [comment]
I have it such that it published the documentation while committing to this branch. So the documentation you see [here](http://phenopackets.org/phenopacket-tools/examples.html) is how we test. Before merging the branch, we will have to change the [pages.yaml](https://github.com/phenopackets/phenopacket-tools/pull/99/files#diff-267452bb53d388a7b14551d9fc53a797edc124dc9085ecc79f5339277a1e53b5) line # 9 to read `main` instead of `develop`

**Comment by hrshdhgd** [comment]
But yes in the future if you want to see if the changes made to the files generated reflect in the documentation, a merge to the `main` branch will trigger the change to be reflected.

**Comment by hrshdhgd** [comment]
Future branch changes will only reflect in the documentation when they are merged to `main`

**Comment by ielis** [comment]
I am converting this to a draft, because we should not really be doing a PR like this. A merge from `develop` to `main` happens through a `release` branch. Let's keep this draft around until we figure out what exactly needs to be accomplished.

**Pull request merged**
