### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by hrshdhgd**
- Test if documentation auto deployment still works
- add the following to the workflow:
  - `mvn clean package`
  - `java -jar phenopacket-tools-cli/target/phenopacket-tools-cli-0.4.6-SNAPSHOT.jar examples`

### CODE REVIEW

**Comment by ielis** [comment]
Hi, 
all `mvn` invocations should be replaced by `./mvnw`. This will use Maven wrapper instead of an arbitrary Maven version that is installed on wherever the build is being run.

I also wonder if we should coordinate CI runs. Based on your proposed changes, the `pages.yml` workflow includes Maven build. However, there is already another workflow `main.yml` that includes the build.
We should make sure we test the build on one step only, right?

**Comment by hrshdhgd** [comment]
Hi @ielis ,

Thanks for the suggestion. Clearly I'm not a Java developer so any advice would be appreciated!

I actually just need the following directories generated by `mvn clean package`:
 - `families`
 - `cohorts`
 - `phenopackets`

If there was a way wherein these directories were possibly generated by `main.yaml` and were accessible to the script when `pages.yml` is running (not aware of how to do this), that would be ideal. For right now I'm just testing it out in this workflow to see I could get the documentation on these files displayed.

**Comment by ielis** [comment]
The `examples` command should generate the examples, basically using the syntax that you included above. Of course, you first must build the JAR file before running the command, and that's where `./mvnw` comes in. 
So, in principle something like the following should work if you put it into the Github workflow:
```shell
./mvnw -Prelease package
java -jar phenopacket-tools-cli/target/phenopacket-tools-cli-0.4.6-SNAPSHOT.jar examples
```

I am a bit worried about the version - it is a part of the JAR name, but it changes and it is not a good idea to just replace it with `*`. That may trick `java` to run Javadoc JAR - also a JAR file and in the folder.

Anyway, to generate the example folders, you do not likely need to run the CI in a matrix. It should be sufficient to run the build and example generation just once, right? E.g. on Ubuntu.

**Comment by hrshdhgd** [comment]
>to generate the example folders, you do not likely need to run the CI in a matrix. It should be sufficient to run the build and example generation just once, right? 

Do you mean generate the examples and push it to GitHub?

**Comment by hrshdhgd** [comment]
This PR is still a work in progress. Sorry Peter, I should have just left it as a draft

**Comment by pnrobinson** [comment]
Sorry, my fault, I was just worried about things getting out of synch!

**Pull request merged**
